// Code generated by MockGen. DO NOT EDIT.
// Source: metrics-collector/internal/server/transport/http/handler (interfaces: MetricsService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_metrics_service.go -package=mocks . MetricsService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "metrics-collector/internal/server/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetricsService is a mock of MetricsService interface.
type MockMetricsService struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsServiceMockRecorder
	isgomock struct{}
}

// MockMetricsServiceMockRecorder is the mock recorder for MockMetricsService.
type MockMetricsServiceMockRecorder struct {
	mock *MockMetricsService
}

// NewMockMetricsService creates a new mock instance.
func NewMockMetricsService(ctrl *gomock.Controller) *MockMetricsService {
	mock := &MockMetricsService{ctrl: ctrl}
	mock.recorder = &MockMetricsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsService) EXPECT() *MockMetricsServiceMockRecorder {
	return m.recorder
}

// GetAllMetrics mocks base method.
func (m *MockMetricsService) GetAllMetrics() ([]models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMetrics")
	ret0, _ := ret[0].([]models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMetrics indicates an expected call of GetAllMetrics.
func (mr *MockMetricsServiceMockRecorder) GetAllMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMetrics", reflect.TypeOf((*MockMetricsService)(nil).GetAllMetrics))
}

// GetMetric mocks base method.
func (m_2 *MockMetricsService) GetMetric(m models.Metrics) (*models.Metrics, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "GetMetric", m)
	ret0, _ := ret[0].(*models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetric indicates an expected call of GetMetric.
func (mr *MockMetricsServiceMockRecorder) GetMetric(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetric", reflect.TypeOf((*MockMetricsService)(nil).GetMetric), m)
}

// UpdateMetric mocks base method.
func (m_2 *MockMetricsService) UpdateMetric(ctx context.Context, m models.Metrics) (*models.Metrics, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpdateMetric", ctx, m)
	ret0, _ := ret[0].(*models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMetric indicates an expected call of UpdateMetric.
func (mr *MockMetricsServiceMockRecorder) UpdateMetric(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetric", reflect.TypeOf((*MockMetricsService)(nil).UpdateMetric), ctx, m)
}

// UpdateMetrics mocks base method.
func (m *MockMetricsService) UpdateMetrics(ctx context.Context, metrics []models.Metrics) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetrics", ctx, metrics)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMetrics indicates an expected call of UpdateMetrics.
func (mr *MockMetricsServiceMockRecorder) UpdateMetrics(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetrics", reflect.TypeOf((*MockMetricsService)(nil).UpdateMetrics), ctx, metrics)
}
