// Code generated by MockGen. DO NOT EDIT.
// Source: metrics-collector/internal/server/transport/grpc (interfaces: MetricsService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_metrics_service.go -package=mocks metrics-collector/internal/server/transport/grpc MetricsService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "metrics-collector/internal/server/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetricsService is a mock of MetricsService interface.
type MockMetricsService struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsServiceMockRecorder
	isgomock struct{}
}

// MockMetricsServiceMockRecorder is the mock recorder for MockMetricsService.
type MockMetricsServiceMockRecorder struct {
	mock *MockMetricsService
}

// NewMockMetricsService creates a new mock instance.
func NewMockMetricsService(ctrl *gomock.Controller) *MockMetricsService {
	mock := &MockMetricsService{ctrl: ctrl}
	mock.recorder = &MockMetricsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsService) EXPECT() *MockMetricsServiceMockRecorder {
	return m.recorder
}

// UpdateMetrics mocks base method.
func (m *MockMetricsService) UpdateMetrics(ctx context.Context, batch []models.Metrics) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetrics", ctx, batch)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMetrics indicates an expected call of UpdateMetrics.
func (mr *MockMetricsServiceMockRecorder) UpdateMetrics(ctx, batch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetrics", reflect.TypeOf((*MockMetricsService)(nil).UpdateMetrics), ctx, batch)
}
