// Code generated by MockGen. DO NOT EDIT.
// Source: metrics-collector/internal/handler (interfaces: MetricsService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_service.go -package=mocks . MetricsService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "metrics-collector/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetricsService is a mock of MetricsService interface.
type MockMetricsService struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsServiceMockRecorder
	isgomock struct{}
}

// MockMetricsServiceMockRecorder is the mock recorder for MockMetricsService.
type MockMetricsServiceMockRecorder struct {
	mock *MockMetricsService
}

// NewMockMetricsService creates a new mock instance.
func NewMockMetricsService(ctrl *gomock.Controller) *MockMetricsService {
	mock := &MockMetricsService{ctrl: ctrl}
	mock.recorder = &MockMetricsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsService) EXPECT() *MockMetricsServiceMockRecorder {
	return m.recorder
}

// GetAllMetrics mocks base method.
func (m *MockMetricsService) GetAllMetrics() ([]models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMetrics")
	ret0, _ := ret[0].([]models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMetrics indicates an expected call of GetAllMetrics.
func (mr *MockMetricsServiceMockRecorder) GetAllMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMetrics", reflect.TypeOf((*MockMetricsService)(nil).GetAllMetrics))
}

// GetMetric mocks base method.
func (m_2 *MockMetricsService) GetMetric(m models.Metrics) (*models.Metrics, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "GetMetric", m)
	ret0, _ := ret[0].(*models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetric indicates an expected call of GetMetric.
func (mr *MockMetricsServiceMockRecorder) GetMetric(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetric", reflect.TypeOf((*MockMetricsService)(nil).GetMetric), m)
}

// GetMetricValue mocks base method.
func (m *MockMetricsService) GetMetricValue(metricType, metricName string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricValue", metricType, metricName)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricValue indicates an expected call of GetMetricValue.
func (mr *MockMetricsServiceMockRecorder) GetMetricValue(metricType, metricName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricValue", reflect.TypeOf((*MockMetricsService)(nil).GetMetricValue), metricType, metricName)
}

// Ping mocks base method.
func (m *MockMetricsService) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockMetricsServiceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockMetricsService)(nil).Ping), ctx)
}

// UpdateMetricByArgs mocks base method.
func (m *MockMetricsService) UpdateMetricByArgs(metricType, metricName, metricValue string) (*models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetricByArgs", metricType, metricName, metricValue)
	ret0, _ := ret[0].(*models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMetricByArgs indicates an expected call of UpdateMetricByArgs.
func (mr *MockMetricsServiceMockRecorder) UpdateMetricByArgs(metricType, metricName, metricValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetricByArgs", reflect.TypeOf((*MockMetricsService)(nil).UpdateMetricByArgs), metricType, metricName, metricValue)
}

// UpdateMetricByJSON mocks base method.
func (m *MockMetricsService) UpdateMetricByJSON(metric models.Metrics) (*models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetricByJSON", metric)
	ret0, _ := ret[0].(*models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMetricByJSON indicates an expected call of UpdateMetricByJSON.
func (mr *MockMetricsServiceMockRecorder) UpdateMetricByJSON(metric any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetricByJSON", reflect.TypeOf((*MockMetricsService)(nil).UpdateMetricByJSON), metric)
}
