// Code generated by MockGen. DO NOT EDIT.
// Source: metrics-collector/internal/server/worker (interfaces: PersistentStorage)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_persistent_storage.go -package=mocks . PersistentStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "metrics-collector/internal/server/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPersistentStorage is a mock of PersistentStorage interface.
type MockPersistentStorage struct {
	ctrl     *gomock.Controller
	recorder *MockPersistentStorageMockRecorder
	isgomock struct{}
}

// MockPersistentStorageMockRecorder is the mock recorder for MockPersistentStorage.
type MockPersistentStorageMockRecorder struct {
	mock *MockPersistentStorage
}

// NewMockPersistentStorage creates a new mock instance.
func NewMockPersistentStorage(ctrl *gomock.Controller) *MockPersistentStorage {
	mock := &MockPersistentStorage{ctrl: ctrl}
	mock.recorder = &MockPersistentStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersistentStorage) EXPECT() *MockPersistentStorageMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockPersistentStorage) GetAll(ctx context.Context) ([]models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPersistentStorageMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPersistentStorage)(nil).GetAll), ctx)
}

// SaveBatch mocks base method.
func (m *MockPersistentStorage) SaveBatch(ctx context.Context, metrics []models.Metrics) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBatch", ctx, metrics)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveBatch indicates an expected call of SaveBatch.
func (mr *MockPersistentStorageMockRecorder) SaveBatch(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBatch", reflect.TypeOf((*MockPersistentStorage)(nil).SaveBatch), ctx, metrics)
}
