// Code generated by MockGen. DO NOT EDIT.
// Source: metrics-collector/internal/server/worker (interfaces: MemStorage)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_mem_storage.go -package=mocks . MemStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "metrics-collector/internal/server/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMemStorage is a mock of MemStorage interface.
type MockMemStorage struct {
	ctrl     *gomock.Controller
	recorder *MockMemStorageMockRecorder
	isgomock struct{}
}

// MockMemStorageMockRecorder is the mock recorder for MockMemStorage.
type MockMemStorageMockRecorder struct {
	mock *MockMemStorage
}

// NewMockMemStorage creates a new mock instance.
func NewMockMemStorage(ctrl *gomock.Controller) *MockMemStorage {
	mock := &MockMemStorage{ctrl: ctrl}
	mock.recorder = &MockMemStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemStorage) EXPECT() *MockMemStorageMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockMemStorage) GetAll() map[string]models.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(map[string]models.Metrics)
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockMemStorageMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockMemStorage)(nil).GetAll))
}

// SaveBatch mocks base method.
func (m *MockMemStorage) SaveBatch(metrics []models.Metrics) *int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBatch", metrics)
	ret0, _ := ret[0].(*int)
	return ret0
}

// SaveBatch indicates an expected call of SaveBatch.
func (mr *MockMemStorageMockRecorder) SaveBatch(metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBatch", reflect.TypeOf((*MockMemStorage)(nil).SaveBatch), metrics)
}
