// Code generated by MockGen. DO NOT EDIT.
// Source: metrics-collector/internal/repository (interfaces: FileStorage)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_file_storage.go -package=mocks metrics-collector/internal/repository FileStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "metrics-collector/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFileStorage is a mock of FileStorage interface.
type MockFileStorage struct {
	ctrl     *gomock.Controller
	recorder *MockFileStorageMockRecorder
	isgomock struct{}
}

// MockFileStorageMockRecorder is the mock recorder for MockFileStorage.
type MockFileStorageMockRecorder struct {
	mock *MockFileStorage
}

// NewMockFileStorage creates a new mock instance.
func NewMockFileStorage(ctrl *gomock.Controller) *MockFileStorage {
	mock := &MockFileStorage{ctrl: ctrl}
	mock.recorder = &MockFileStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStorage) EXPECT() *MockFileStorageMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockFileStorage) GetAll() ([]models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockFileStorageMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockFileStorage)(nil).GetAll))
}

// SaveBatch mocks base method.
func (m *MockFileStorage) SaveBatch(metrics []models.Metrics) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBatch", metrics)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveBatch indicates an expected call of SaveBatch.
func (mr *MockFileStorageMockRecorder) SaveBatch(metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBatch", reflect.TypeOf((*MockFileStorage)(nil).SaveBatch), metrics)
}

// SaveMetric mocks base method.
func (m *MockFileStorage) SaveMetric(metric models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMetric", metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMetric indicates an expected call of SaveMetric.
func (mr *MockFileStorageMockRecorder) SaveMetric(metric any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMetric", reflect.TypeOf((*MockFileStorage)(nil).SaveMetric), metric)
}
