// Code generated by cmd/reset; DO NOT EDIT.
package handler

func (x *MetricsHandler) Reset() {
	if x == nil {
		return
	}

	var serviceZero MetricsService
	x.service = serviceZero
	if v, ok := interface{}(&x.service).(interface{ Reset() }); ok {
		v.Reset()
	}
	if x.logger != nil {
		if v, ok := interface{}(&*x.logger).(interface{ Reset() }); ok {
			v.Reset()
		}
	}
	if x.allMetricsHTMLTemplate != nil {
		if v, ok := interface{}(&*x.allMetricsHTMLTemplate).(interface{ Reset() }); ok {
			v.Reset()
		}
	}
}
