// Code generated by MockGen. DO NOT EDIT.
// Source: metrics-collector/internal/server/transport/http/middleware (interfaces: AuditPublisher)
//
// Generated by this command:
//
//	mockgen -destination=mocks/audit_publisher.go -package=mocks . AuditPublisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	audit "metrics-collector/internal/domain/audit"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuditPublisher is a mock of AuditPublisher interface.
type MockAuditPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockAuditPublisherMockRecorder
	isgomock struct{}
}

// MockAuditPublisherMockRecorder is the mock recorder for MockAuditPublisher.
type MockAuditPublisherMockRecorder struct {
	mock *MockAuditPublisher
}

// NewMockAuditPublisher creates a new mock instance.
func NewMockAuditPublisher(ctrl *gomock.Controller) *MockAuditPublisher {
	mock := &MockAuditPublisher{ctrl: ctrl}
	mock.recorder = &MockAuditPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditPublisher) EXPECT() *MockAuditPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockAuditPublisher) Publish(event audit.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", event)
}

// Publish indicates an expected call of Publish.
func (mr *MockAuditPublisherMockRecorder) Publish(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockAuditPublisher)(nil).Publish), event)
}
