CREATE TABLE IF NOT EXISTS counters (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  value INTEGER NOT NULL,
  updated_dt TIMESTAMP WITH TIME ZONE DEfAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS gauges (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  value DOUBLE PRECISION NOT NULL,
  updated_dt TIMESTAMP WITH TIME ZONE DEfAULT CURRENT_TIMESTAMP
);