// Code generated by MockGen. DO NOT EDIT.
// Source: metrics-collector/internal/proto (interfaces: MetricsClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_metrics_client.go -package=mocks metrics-collector/internal/proto MetricsClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	proto "metrics-collector/internal/proto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockMetricsClient is a mock of MetricsClient interface.
type MockMetricsClient struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsClientMockRecorder
	isgomock struct{}
}

// MockMetricsClientMockRecorder is the mock recorder for MockMetricsClient.
type MockMetricsClientMockRecorder struct {
	mock *MockMetricsClient
}

// NewMockMetricsClient creates a new mock instance.
func NewMockMetricsClient(ctrl *gomock.Controller) *MockMetricsClient {
	mock := &MockMetricsClient{ctrl: ctrl}
	mock.recorder = &MockMetricsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsClient) EXPECT() *MockMetricsClientMockRecorder {
	return m.recorder
}

// UpdateMetrics mocks base method.
func (m *MockMetricsClient) UpdateMetrics(ctx context.Context, in *proto.UpdateMetricsRequest, opts ...grpc.CallOption) (*proto.UpdateMetricsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateMetrics", varargs...)
	ret0, _ := ret[0].(*proto.UpdateMetricsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMetrics indicates an expected call of UpdateMetrics.
func (mr *MockMetricsClientMockRecorder) UpdateMetrics(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetrics", reflect.TypeOf((*MockMetricsClient)(nil).UpdateMetrics), varargs...)
}
