// Code generated by cmd/reset; DO NOT EDIT.
package models

func (x *Metrics) Reset() {
	if x == nil {
		return
	}

	x.ID = ""
	x.MType = ""
	if x.Delta != nil {
		*x.Delta = 0
	}
	if x.Value != nil {
		*x.Value = 0
	}
	x.Hash = ""
}
