// Утилита для автоматической генерации методов Reset()
// для структур, помеченных комментарием // generate:reset.
//
// Утилита сканирует все пакеты проекта, начиная с корневой директории,
// и для каждой структуры с комментарием // generate:reset генерирует
// метод сброса состояния к начальным значениям.
//
// Правила генерации:
//   - Примитивные типы сбрасываются к нулевым значениям (0, "", false)
//   - Слайсы обрезаются до нулевой длины (s = s[:0])
//   - Map очищаются через встроенную функцию clear()
//   - Указатели проверяются на nil и сбрасываются по тем же правилам
//   - Вложенные структуры с методом Reset() вызывают его
//
// Сгенерированный код помещается в файл reset.gen.go в том же пакете,
// где найдена структура.
//
// Использование:
//
//	go run ./cmd/reset/main.go
//
// Или после сборки:
//
//	go build -o reset-gen ./cmd/reset/
//	./reset-gen
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

func main() {
	root, err := os.Getwd()
	if err != nil {
		log.Fatalf("Error getting working directory: %v", err)
	}

	if err := processDir(root); err != nil {
		log.Fatalf("Error: %v", err)
	}
}

func processDir(root string) error {
	processed := make(map[string]bool)

	return filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() {
			base := d.Name()
			if base == ".git" || base == "vendor" || base == ".idea" ||
				strings.HasPrefix(base, ".") || base == "cmd" {
				return filepath.SkipDir
			}
			return nil
		}

		if !strings.HasSuffix(d.Name(), ".go") ||
			strings.HasSuffix(d.Name(), "_test.go") ||
			d.Name() == "reset.gen.go" {
			return nil
		}

		dir := filepath.Dir(path)
		if processed[dir] {
			return nil
		}
		processed[dir] = true

		return processPackage(dir)
	})
}

func processPackage(dir string) error {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax | packages.NeedTypes,
		Dir:  dir,
	}

	pkgs, err := packages.Load(cfg, ".")
	if err != nil {
		return fmt.Errorf("loading package %s: %w", dir, err)
	}

	if packages.PrintErrors(pkgs) > 0 {
		return fmt.Errorf("errors loading package %s", dir)
	}

	var targets []targetStruct
	for _, pkg := range pkgs {
		for _, file := range pkg.Syntax {
			ast.Inspect(file, func(n ast.Node) bool {
				genDecl, ok := n.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					return true
				}
				if !hasGenerateResetComment(genDecl.Doc) {
					return true
				}

				for _, spec := range genDecl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					_, isStruct := typeSpec.Type.(*ast.StructType)
					if isStruct {
						targets = append(targets, targetStruct{
							Name: typeSpec.Name.Name,
							Spec: typeSpec,
						})
					}
				}
				return true
			})
		}
	}

	if len(targets) == 0 {
		return nil
	}

	buf := &bytes.Buffer{}
	pkgName := "unknown"
	if len(pkgs) > 0 {
		pkgName = pkgs[0].Name
	}

	fmt.Fprintf(buf, "// Package %s provides generated Reset methods.\n", pkgName)
	fmt.Fprintf(buf, "// Code generated by cmd/reset; DO NOT EDIT.\n")
	fmt.Fprintf(buf, "package %s\n\n", pkgName)

	for _, ts := range targets {
		genResetMethod(buf, ts.Name, ts.Spec.Type.(*ast.StructType))
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("formatting generated code in %s: %w", dir, err)
	}

	outPath := filepath.Join(dir, "reset.gen.go")
	if err := os.WriteFile(outPath, src, 0644); err != nil {
		return fmt.Errorf("writing %s: %w", outPath, err)
	}
	fmt.Printf("Generated %s\n", outPath)
	return nil
}

type targetStruct struct {
	Name string
	Spec *ast.TypeSpec
}

func hasGenerateResetComment(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		if strings.TrimSpace(c.Text) == "// generate:reset" {
			return true
		}
	}
	return false
}

func genResetMethod(buf *bytes.Buffer, structName string, st *ast.StructType) {
	fmt.Fprintf(buf, "func (x *%s) Reset() {\n", structName)
	buf.WriteString("\tif x == nil {\n\t\treturn\n\t}\n\n")

	for _, field := range st.Fields.List {
		for _, name := range field.Names {
			genFieldReset(buf, name.Name, field.Type)
		}
	}

	buf.WriteString("}\n\n")
}

func genFieldReset(buf *bytes.Buffer, fieldName string, expr ast.Expr) {
	accessor := fmt.Sprintf("x.%s", fieldName)

	switch t := expr.(type) {
	case *ast.Ident:
		genIdentReset(buf, fieldName, accessor, t)
	case *ast.StarExpr:
		genPointerReset(buf, fieldName, accessor, t.X)
	case *ast.ArrayType:
		fmt.Fprintf(buf, "\t%s = %s[:0]\n", accessor, accessor)
	case *ast.MapType:
		fmt.Fprintf(buf, "\tclear(%s)\n", accessor)
	default:
		fmt.Fprintf(buf, "\tif v, ok := interface{}(%s).(interface{ Reset() }); ok {\n", accessor)
		buf.WriteString("\t\tv.Reset()\n\t}\n")
	}
}

func genIdentReset(buf *bytes.Buffer, fieldName, accessor string, id *ast.Ident) {
	switch id.Name {
	case "string":
		fmt.Fprintf(buf, "\t%s = \"\"\n", accessor)
	case "bool":
		fmt.Fprintf(buf, "\t%s = false\n", accessor)
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64", "complex64", "complex128",
		"byte", "rune", "uintptr":
		fmt.Fprintf(buf, "\t%s = 0\n", accessor)
	default:
		fmt.Fprintf(buf, "\tvar zero %s\n", id.Name)
		fmt.Fprintf(buf, "\t%s = zero\n", accessor)
		fmt.Fprintf(buf, "\tif v, ok := interface{}(%s).(interface{ Reset() }); ok {\n", accessor)
		buf.WriteString("\t\tv.Reset()\n\t}\n")
	}
}

func genPointerReset(buf *bytes.Buffer, fieldName, accessor string, baseType ast.Expr) {
	fmt.Fprintf(buf, "\tif %s != nil {\n", accessor)
	deref := fmt.Sprintf("*%s", accessor)

	switch t := baseType.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			fmt.Fprintf(buf, "\t\t%s = \"\"\n", deref)
		case "bool":
			fmt.Fprintf(buf, "\t\t%s = false\n", deref)
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64", "complex64", "complex128",
			"byte", "rune", "uintptr":
			fmt.Fprintf(buf, "\t\t%s = 0\n", deref)
		default:
			fmt.Fprintf(buf, "\t\tvar zero %s\n", t.Name)
			fmt.Fprintf(buf, "\t\t%s = zero\n", deref)
		}
	case *ast.ArrayType:
		fmt.Fprintf(buf, "\t\t%s = %s[:0]\n", deref, deref)
	case *ast.MapType:
		fmt.Fprintf(buf, "\t\tclear(%s)\n", deref)
	default:
		fmt.Fprintf(buf, "\t\tif v, ok := interface{}(%s).(interface{ Reset() }); ok {\n", deref)
		buf.WriteString("\t\t\tv.Reset()\n\t\t}\n")
	}
	buf.WriteString("\t}\n")
}
