// ./cmd/reset/main.go
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	root, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error getting working directory: %v\n", err)
		os.Exit(1)
	}

	if err := processDir(root); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func processDir(root string) error {
	return filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() {
			base := d.Name()
			if base == ".git" || base == "vendor" || base == ".idea" || strings.HasPrefix(base, ".") {
				return filepath.SkipDir
			}
			return nil
		}

		if !strings.HasSuffix(d.Name(), ".go") ||
			strings.HasSuffix(d.Name(), "_test.go") ||
			d.Name() == "reset.gen.go" {
			return nil
		}

		dir := filepath.Dir(path)
		return processPackage(dir)
	})
}

func processPackage(dir string) error {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go") && fi.Name() != "reset.gen.go"
	}, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("parsing dir %s: %w", dir, err)
	}

	var targets []targetStruct
	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			ast.Inspect(file, func(n ast.Node) bool {
				genDecl, ok := n.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					return true
				}
				if !hasGenerateResetComment(genDecl.Doc) {
					return true
				}

				for _, spec := range genDecl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					_, isStruct := typeSpec.Type.(*ast.StructType)
					if isStruct {
						targets = append(targets, targetStruct{
							Name: typeSpec.Name.Name,
							Spec: typeSpec,
						})
					}
				}
				return true
			})
		}
	}

	if len(targets) == 0 {
		return nil
	}

	buf := &bytes.Buffer{}
	pkgName := "unknown"
	for _, pkg := range pkgs {
		pkgName = pkg.Name
		break
	}

	buf.WriteString(fmt.Sprintf("// Code generated by cmd/reset; DO NOT EDIT.\npackage %s\n\n", pkgName))

	for _, ts := range targets {
		genResetMethod(buf, ts.Name, ts.Spec.Type.(*ast.StructType))
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("formatting generated code in %s: %w", dir, err)
	}

	outPath := filepath.Join(dir, "reset.gen.go")
	if err := os.WriteFile(outPath, src, 0644); err != nil {
		return fmt.Errorf("writing %s: %w", outPath, err)
	}
	fmt.Printf("Generated %s\n", outPath)
	return nil
}

type targetStruct struct {
	Name string
	Spec *ast.TypeSpec
}

func hasGenerateResetComment(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		if strings.TrimSpace(c.Text) == "// generate:reset" {
			return true
		}
	}
	return false
}

func genResetMethod(buf *bytes.Buffer, structName string, st *ast.StructType) {
	fmt.Fprintf(buf, "func (x *%s) Reset() {\n", structName)
	buf.WriteString("\tif x == nil {\n\t\treturn\n\t}\n\n")

	for _, field := range st.Fields.List {
		for _, name := range field.Names {
			genFieldReset(buf, name.Name, field.Type)
		}
	}

	buf.WriteString("}\n\n")
}

func genFieldReset(buf *bytes.Buffer, fieldName string, expr ast.Expr) {
	accessor := fmt.Sprintf("x.%s", fieldName)

	switch t := expr.(type) {
	case *ast.Ident:
		genIdentReset(buf, fieldName, accessor, t)
	case *ast.StarExpr:
		genPointerReset(buf, fieldName, accessor, t.X)
	case *ast.ArrayType:
		buf.WriteString(fmt.Sprintf("\t%s = %s[:0]\n", accessor, accessor))
	case *ast.MapType:
		buf.WriteString(fmt.Sprintf("\tclear(%s)\n", accessor))
	case *ast.SelectorExpr:
		buf.WriteString(fmt.Sprintf("\tif v, ok := interface{}(&%s).(interface{ Reset() }); ok {\n", accessor))
		buf.WriteString(fmt.Sprintf("\t\tv.Reset()\n\t}\n"))
	default:
		buf.WriteString(fmt.Sprintf("\tif v, ok := interface{}(&%s).(interface{ Reset() }); ok {\n", accessor))
		buf.WriteString(fmt.Sprintf("\t\tv.Reset()\n\t}\n"))
	}
}

func genIdentReset(buf *bytes.Buffer, fieldName, accessor string, id *ast.Ident) {
	switch id.Name {
	case "string":
		buf.WriteString(fmt.Sprintf("\t%s = \"\"\n", accessor))
	case "bool":
		buf.WriteString(fmt.Sprintf("\t%s = false\n", accessor))
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64", "complex64", "complex128",
		"byte", "rune", "uintptr":
		buf.WriteString(fmt.Sprintf("\t%s = 0\n", accessor))
	default:
		varName := fmt.Sprintf("%sZero", fieldName)
		buf.WriteString(fmt.Sprintf("\tvar %s %s\n", varName, id.Name))
		buf.WriteString(fmt.Sprintf("\t%s = %s\n", accessor, varName))
		buf.WriteString(fmt.Sprintf("\tif v, ok := interface{}(&%s).(interface{ Reset() }); ok {\n", accessor))
		buf.WriteString(fmt.Sprintf("\t\tv.Reset()\n\t}\n"))
	}
}

func genPointerReset(buf *bytes.Buffer, fieldName, accessor string, baseType ast.Expr) {
	buf.WriteString(fmt.Sprintf("\tif %s != nil {\n", accessor))
	deref := fmt.Sprintf("*%s", accessor)

	switch t := baseType.(type) {
	case *ast.Ident:
		genIdentReset(buf, fieldName, deref, t)
	case *ast.ArrayType:
		buf.WriteString(fmt.Sprintf("\t\t%s = %s[:0]\n", deref, deref))
	case *ast.MapType:
		buf.WriteString(fmt.Sprintf("\t\tclear(%s)\n", deref))
	case *ast.StarExpr:
		buf.WriteString(fmt.Sprintf("\t\t%s.Reset()\n", deref))
	case *ast.SelectorExpr:
		buf.WriteString(fmt.Sprintf("\t\tif v, ok := interface{}(&%s).(interface{ Reset() }); ok {\n", deref))
		buf.WriteString(fmt.Sprintf("\t\t\tv.Reset()\n\t\t}\n"))
	default:
		buf.WriteString(fmt.Sprintf("\t\tif v, ok := interface{}(&%s).(interface{ Reset() }); ok {\n", deref))
		buf.WriteString(fmt.Sprintf("\t\t\tv.Reset()\n\t\t}\n"))
	}
	buf.WriteString("\t}\n")
}
