// Code generated by cmd/reset; DO NOT EDIT.
package store

func (x *Store) Reset() {
	if x == nil {
		return
	}

	clear(x.metrics)
	if v, ok := interface{}(&x.mu).(interface{ Reset() }); ok {
		v.Reset()
	}
}
