// Code generated by cmd/reset; DO NOT EDIT.
package agent

func (x *Agent) Reset() {
	if x == nil {
		return
	}

	if x.cfg != nil {
		if v, ok := interface{}(&*x.cfg).(interface{ Reset() }); ok {
			v.Reset()
		}
	}
	if x.logger != nil {
		if v, ok := interface{}(&*x.logger).(interface{ Reset() }); ok {
			v.Reset()
		}
	}
	if x.gzip != nil {
		if v, ok := interface{}(&*x.gzip).(interface{ Reset() }); ok {
			v.Reset()
		}
	}
	if x.store != nil {
		if v, ok := interface{}(&*x.store).(interface{ Reset() }); ok {
			v.Reset()
		}
	}
	if x.poller != nil {
		if v, ok := interface{}(&*x.poller).(interface{ Reset() }); ok {
			v.Reset()
		}
	}
	if x.reporter != nil {
		if v, ok := interface{}(&*x.reporter).(interface{ Reset() }); ok {
			v.Reset()
		}
	}
}
