// Code generated by cmd/reset; DO NOT EDIT.
package worker

func (x *Reporter) Reset() {
	if x == nil {
		return
	}

	var clientZero Client
	x.client = clientZero
	if v, ok := interface{}(&x.client).(interface{ Reset() }); ok {
		v.Reset()
	}
	var storeZero ReporterStore
	x.store = storeZero
	if v, ok := interface{}(&x.store).(interface{ Reset() }); ok {
		v.Reset()
	}
	if x.logger != nil {
		if v, ok := interface{}(&*x.logger).(interface{ Reset() }); ok {
			v.Reset()
		}
	}
	x.reportInterval = 0
	if v, ok := interface{}(&x.jobs).(interface{ Reset() }); ok {
		v.Reset()
	}
	x.workers = 0
}

func (x *Poller) Reset() {
	if x == nil {
		return
	}

	var storeZero PollerStore
	x.store = storeZero
	if v, ok := interface{}(&x.store).(interface{ Reset() }); ok {
		v.Reset()
	}
	if x.logger != nil {
		if v, ok := interface{}(&*x.logger).(interface{ Reset() }); ok {
			v.Reset()
		}
	}
	x.pollInterval = 0
}
