// Code generated by MockGen. DO NOT EDIT.
// Source: metrics-collector/internal/service (interfaces: MetricsRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_metrics_repository.go -package=mocks . MetricsRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "metrics-collector/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetricsRepository is a mock of MetricsRepository interface.
type MockMetricsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsRepositoryMockRecorder
	isgomock struct{}
}

// MockMetricsRepositoryMockRecorder is the mock recorder for MockMetricsRepository.
type MockMetricsRepositoryMockRecorder struct {
	mock *MockMetricsRepository
}

// NewMockMetricsRepository creates a new mock instance.
func NewMockMetricsRepository(ctrl *gomock.Controller) *MockMetricsRepository {
	mock := &MockMetricsRepository{ctrl: ctrl}
	mock.recorder = &MockMetricsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsRepository) EXPECT() *MockMetricsRepositoryMockRecorder {
	return m.recorder
}

// GetAllMetrics mocks base method.
func (m *MockMetricsRepository) GetAllMetrics() map[string]models.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMetrics")
	ret0, _ := ret[0].(map[string]models.Metrics)
	return ret0
}

// GetAllMetrics indicates an expected call of GetAllMetrics.
func (mr *MockMetricsRepositoryMockRecorder) GetAllMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMetrics", reflect.TypeOf((*MockMetricsRepository)(nil).GetAllMetrics))
}

// GetMetric mocks base method.
func (m *MockMetricsRepository) GetMetric(metricName string) (*models.Metrics, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetric", metricName)
	ret0, _ := ret[0].(*models.Metrics)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetMetric indicates an expected call of GetMetric.
func (mr *MockMetricsRepositoryMockRecorder) GetMetric(metricName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetric", reflect.TypeOf((*MockMetricsRepository)(nil).GetMetric), metricName)
}

// SaveMetric mocks base method.
func (m *MockMetricsRepository) SaveMetric(ctx context.Context, metric models.Metrics) (*models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMetric", ctx, metric)
	ret0, _ := ret[0].(*models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveMetric indicates an expected call of SaveMetric.
func (mr *MockMetricsRepositoryMockRecorder) SaveMetric(ctx, metric any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMetric", reflect.TypeOf((*MockMetricsRepository)(nil).SaveMetric), ctx, metric)
}

// SaveMetricsBatch mocks base method.
func (m *MockMetricsRepository) SaveMetricsBatch(ctx context.Context, metrics []models.Metrics) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMetricsBatch", ctx, metrics)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveMetricsBatch indicates an expected call of SaveMetricsBatch.
func (mr *MockMetricsRepositoryMockRecorder) SaveMetricsBatch(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMetricsBatch", reflect.TypeOf((*MockMetricsRepository)(nil).SaveMetricsBatch), ctx, metrics)
}
