// Code generated by cmd/reset; DO NOT EDIT.
package audit

func (x *Publisher) Reset() {
	if x == nil {
		return
	}

	if v, ok := interface{}(&x.events).(interface{ Reset() }); ok {
		v.Reset()
	}
	x.handlers = x.handlers[:0]
	if x.logger != nil {
		if v, ok := interface{}(&*x.logger).(interface{ Reset() }); ok {
			v.Reset()
		}
	}
	if v, ok := interface{}(&x.wg).(interface{ Reset() }); ok {
		v.Reset()
	}
}
