CREATE TABLE IF NOT EXISTS counters (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(255) NOT NULL UNIQUE,
  value BIGINT NOT NULL,
  updated_dt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS gauges (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(255) NOT NULL UNIQUE,
  value DOUBLE PRECISION NOT NULL,
  updated_dt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);