// Code generated by MockGen. DO NOT EDIT.
// Source: metrics-collector/internal/agent/worker (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_store.go -package=mocks . Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// GetMetricsSnapshot mocks base method.
func (m *MockStore) GetMetricsSnapshot() map[string]float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricsSnapshot")
	ret0, _ := ret[0].(map[string]float64)
	return ret0
}

// GetMetricsSnapshot indicates an expected call of GetMetricsSnapshot.
func (mr *MockStoreMockRecorder) GetMetricsSnapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricsSnapshot", reflect.TypeOf((*MockStore)(nil).GetMetricsSnapshot))
}

// UpdateMetrics mocks base method.
func (m *MockStore) UpdateMetrics(metrics map[string]float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateMetrics", metrics)
}

// UpdateMetrics indicates an expected call of UpdateMetrics.
func (mr *MockStoreMockRecorder) UpdateMetrics(metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetrics", reflect.TypeOf((*MockStore)(nil).UpdateMetrics), metrics)
}
