// Code generated by MockGen. DO NOT EDIT.
// Source: metrics-collector/internal/agent/worker (interfaces: ReporterStore)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_reporter_store.go -package=mocks . ReporterStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReporterStore is a mock of ReporterStore interface.
type MockReporterStore struct {
	ctrl     *gomock.Controller
	recorder *MockReporterStoreMockRecorder
	isgomock struct{}
}

// MockReporterStoreMockRecorder is the mock recorder for MockReporterStore.
type MockReporterStoreMockRecorder struct {
	mock *MockReporterStore
}

// NewMockReporterStore creates a new mock instance.
func NewMockReporterStore(ctrl *gomock.Controller) *MockReporterStore {
	mock := &MockReporterStore{ctrl: ctrl}
	mock.recorder = &MockReporterStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReporterStore) EXPECT() *MockReporterStoreMockRecorder {
	return m.recorder
}

// GetMetricsSnapshot mocks base method.
func (m *MockReporterStore) GetMetricsSnapshot() map[string]float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricsSnapshot")
	ret0, _ := ret[0].(map[string]float64)
	return ret0
}

// GetMetricsSnapshot indicates an expected call of GetMetricsSnapshot.
func (mr *MockReporterStoreMockRecorder) GetMetricsSnapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricsSnapshot", reflect.TypeOf((*MockReporterStore)(nil).GetMetricsSnapshot))
}

// UpdateMetrics mocks base method.
func (m *MockReporterStore) UpdateMetrics(metrics map[string]float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateMetrics", metrics)
}

// UpdateMetrics indicates an expected call of UpdateMetrics.
func (mr *MockReporterStoreMockRecorder) UpdateMetrics(metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetrics", reflect.TypeOf((*MockReporterStore)(nil).UpdateMetrics), metrics)
}
