// Code generated by MockGen. DO NOT EDIT.
// Source: metrics-collector/internal/agent/worker (interfaces: PollerStore)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_poller_store.go -package=mocks . PollerStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPollerStore is a mock of PollerStore interface.
type MockPollerStore struct {
	ctrl     *gomock.Controller
	recorder *MockPollerStoreMockRecorder
	isgomock struct{}
}

// MockPollerStoreMockRecorder is the mock recorder for MockPollerStore.
type MockPollerStoreMockRecorder struct {
	mock *MockPollerStore
}

// NewMockPollerStore creates a new mock instance.
func NewMockPollerStore(ctrl *gomock.Controller) *MockPollerStore {
	mock := &MockPollerStore{ctrl: ctrl}
	mock.recorder = &MockPollerStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPollerStore) EXPECT() *MockPollerStoreMockRecorder {
	return m.recorder
}

// UpdateMetrics mocks base method.
func (m *MockPollerStore) UpdateMetrics(metrics map[string]float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateMetrics", metrics)
}

// UpdateMetrics indicates an expected call of UpdateMetrics.
func (mr *MockPollerStoreMockRecorder) UpdateMetrics(metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetrics", reflect.TypeOf((*MockPollerStore)(nil).UpdateMetrics), metrics)
}
