// Code generated by cmd/reset; DO NOT EDIT.
package config

func (x *AgentConfig) Reset() {
	if x == nil {
		return
	}

	x.PollInterval = 0
	x.ReportInterval = 0
	x.ServerBaseURL = ""
	x.SecretKey = ""
	x.RateLimit = 0
}

func (x *ServerConfig) Reset() {
	if x == nil {
		return
	}

	x.ServerBaseURL = ""
	x.StoreInterval = 0
	x.FileStoragePath = ""
	x.Restore = false
	x.DatabaseDSN = ""
	x.SecretKey = ""
	if v, ok := interface{}(&x.RequestTimeout).(interface{ Reset() }); ok {
		v.Reset()
	}
	if v, ok := interface{}(&x.ShutdownTimeout).(interface{ Reset() }); ok {
		v.Reset()
	}
	x.AuditFile = ""
	x.AuditURL = ""
	x.PprofAddr = ""
}
