// Package dto provides generated Reset methods.
// Code generated by cmd/reset; DO NOT EDIT.
package dto

func (x *Metric) Reset() {
	if x == nil {
		return
	}

	x.ID = ""
	x.Type = ""
	if x.Delta != nil {
		*x.Delta = 0
	}
	if x.Value != nil {
		*x.Value = 0
	}
}
