// Code generated by cmd/reset; DO NOT EDIT.
package client

func (x *Client) Reset() {
	if x == nil {
		return
	}

	x.baseURL = ""
	x.secretKey = ""
	if x.httpClient != nil {
		if v, ok := interface{}(&*x.httpClient).(interface{ Reset() }); ok {
			v.Reset()
		}
	}
	if x.gzip != nil {
		if v, ok := interface{}(&*x.gzip).(interface{ Reset() }); ok {
			v.Reset()
		}
	}
	if x.logger != nil {
		if v, ok := interface{}(&*x.logger).(interface{ Reset() }); ok {
			v.Reset()
		}
	}
}
