// Code generated by MockGen. DO NOT EDIT.
// Source: metrics-collector/internal/repository (interfaces: PostgresStorage)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_postgres_storage.go -package=mocks metrics-collector/internal/repository PostgresStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "metrics-collector/internal/server/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPostgresStorage is a mock of PostgresStorage interface.
type MockPostgresStorage struct {
	ctrl     *gomock.Controller
	recorder *MockPostgresStorageMockRecorder
	isgomock struct{}
}

// MockPostgresStorageMockRecorder is the mock recorder for MockPostgresStorage.
type MockPostgresStorageMockRecorder struct {
	mock *MockPostgresStorage
}

// NewMockPostgresStorage creates a new mock instance.
func NewMockPostgresStorage(ctrl *gomock.Controller) *MockPostgresStorage {
	mock := &MockPostgresStorage{ctrl: ctrl}
	mock.recorder = &MockPostgresStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostgresStorage) EXPECT() *MockPostgresStorageMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockPostgresStorage) GetAll(ctx context.Context) ([]models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPostgresStorageMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPostgresStorage)(nil).GetAll), ctx)
}

// Ping mocks base method.
func (m *MockPostgresStorage) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockPostgresStorageMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockPostgresStorage)(nil).Ping), ctx)
}

// SaveBatch mocks base method.
func (m *MockPostgresStorage) SaveBatch(ctx context.Context, metrics []models.Metrics) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBatch", ctx, metrics)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveBatch indicates an expected call of SaveBatch.
func (mr *MockPostgresStorageMockRecorder) SaveBatch(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBatch", reflect.TypeOf((*MockPostgresStorage)(nil).SaveBatch), ctx, metrics)
}

// SaveMetric mocks base method.
func (m_2 *MockPostgresStorage) SaveMetric(ctx context.Context, m models.Metrics) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SaveMetric", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMetric indicates an expected call of SaveMetric.
func (mr *MockPostgresStorageMockRecorder) SaveMetric(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMetric", reflect.TypeOf((*MockPostgresStorage)(nil).SaveMetric), ctx, m)
}
